ASSANDRA:
  CLUSTER_IP:
    - 127.0.0.1
  KEYSPACE: beeketing
  USERNAME:
  PASSWORD:
  PORT: 9042

MONGODB:
  HOST: 127.0.0.1
  PORT: 27017
  DBNAME: beeketing

MONGODB_PRODUCTION:
  HOST: 127.0.0.1
  PORT: 27017
  DBNAME: beeketing
#  HOST: 10.136.13.219
#  PORT: 27020
#  DBNAME: beeketing

SYSTEM:
  CORES: 4
  BATCH_SIZE: 1000

POSTGRESQL:
  HOST: 52.173.243.64
  PORT: 5432
  DBNAME: analytics
  USERNAME: dev
  PASSWORD: EYrKONX9nyP2